[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "vizdantic"
version = "0.0.1"
description = "Visualistion validation using Pydantic for ai agents"
requires-python = ">=3.10"
license = "MIT"
dependencies = [
    "pydantic>=2.11.9",
]

[tool.hatch.build.targets.wheel]
packages = ["vizdantic"]

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]

[tool.ruff.format]
quote-style = "single"

[tool.uv]
required-version = ">=0.8.0"
